---
title: "My PGWP flagpoling experience"
author: "Steven Leung"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This page was last updated on April 25, 2024.  Since CBSA has stopped allowing for flagpoling of PGWP, I am archiving this page and it will no longer be maintained. 

## Disclaimer

1.  This sharing is anecdotal only. My success is not statistical significant (sample size = 1). :-)
2.  There is no guarantee of success. And even if you did the same thing, you might still get a different result.
3.  This is not for profit and it is merely for helping out friends like you. So it is not any kind of immigration consultancy. Please consult the registered professionals as necessary.

## Background

1.  I applied for PGWP on July 5, 2022. After getting the "WP-EXT" letter from the GCKey system almost the same day, I never saw any update from IRCC again;
2.  My "WP-EXT" has an expiry date of Nov 2, 2022 on it. On Oct 21, 2022, I submitted a "webform" to IRCC requesting a new letter with an extended expiry.  No response yet.

## Process

### Day 1

1.  I went there one day and arrived at the Boundary Bay Border Crossing (address: 4 56th St., Delta, BC).  The other side of the border is Point Roberts, WA, USA.
2.  I parked my car right outside (on the north side of) the office.
3.  (FLAGPOLING) Then I walked as a pedestrian past the office on its right (west) side, then across the "border" which is a paved road to the booth guarded by a US border officer.  Then he asked me what I wanted to do.  I said I am "flagpoling".  Then he said "Okay, you can go back now.  Have a nice day."  I asked him if he needed to stamp on my passport or give me a card, etc. He said no.  Then I turned around and walked back to Canada, but this time I walked back to Canada on the right (east) side of the building.  Then, as a pedestrian, I walked to the booth guarded by Canada's CBSA.  Then she asked me what I wanted to apply for, whether I have already applied or already been approved, etc.  Then she put a yellow card inside my passport, and asked me to go back into the office through its main entrance (facing where I parked my car).
4. Then another officer talked to me, showing me a checklist (details below) of things for applying for PGWP.  He asked me whether I am ready to apply for PGWP.  I said I was ready, and I was asked to pay CAD155 again for PGWP.  He said that if it is not successful, it will be all that cost.  If it is successful, there will be another CAD100 for the open work permit.  If for some reason they can't find my biometrics in the system, there will be another charge for the biometrics (which I forgot how much).
5. After paying the CAD155, a interview appointment is set up for me the next Monday (Day 2).  

### Day 2

1. I reported there more than 30 minutes early, and they just asked me to sit there and wait.  When it was time, I stood up and told them that I am there.
2. Later an officer asked for me and asked me a few questions.  
- Where did I study?
- What did I study?
- How long was the duration? I told him that the program was 10 months long, but it was equivalent to a full 24-month in terms of workload.  Then he asked "Was it accelerated?".  Apparently he was looking for the keyword "Accelerated."  He then also asked whether it is mentioned in the letter of completion.  Thanks to Milad, it is mentioned there!!!
- What kind of program was it?  Was it diploma?  Then I said "Master's DEGREE" (much emphasis on the word "degree").
3. Then our conversation ended and I went back to waiting.
4. In the middle of that waiting, the cashier lady (she was the only person not in uniform) asked me to pay another CAD100 for "open work permit".  And I did.
5. After a while, the officer called and I was given the PGWP and all the other documents were returned.

## Checklist of documents to bring:
1. Passport 
- You don't need US visa to flagpole. Just be careful not to drive straight into the US.  I recommend that you park and flagpole as a pedestrian.
- Just like the Study Permit, it will not go beyond the expiry of your passport.  So make sure that your passport has at least 3 years on it.
2. letter of completion or diploma - hard copy
3. official transcript - Order with SCC and pick up on campus.
4. No need to fill out the same forms again.  Apparently they will get it from the system or they just don't need them.
5. A letter of explanation - optional but recommended - Due to the fact that whether CBSA processes the PGWP or not is totally discretionary, I was prepared to justify it with some reasons of urgency.  The friend who succeeded in flagpoling recommended that I wrote a letter of explanation and I did.  I was still prepared to talk about my situation orally, but having it in concise writing will help.
