---
comment: |
  This file is my data-driven resume.  It can be used for generating HTML, PDF and Word versions of the resume.
  If a text (actually Markdown) version is desired, the following command can be used:
  Rscript -e "rmarkdown::render('Resume_of_Steven_leung.Rmd', output_format='md_document')"
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document:
    latex_engine: xelatex
fontsize: 11pt
header-includes: |-
  \usepackage[T1]{fontenc} 
  \usepackage[utf8]{inputenc}
  % It allows me to place the tables or images where I want, whether there is space or not \usepackage{float}
  % It has several commands to have more control over the tables (at least I use it for this) \usepackage{array}
  % For custom headers and footers \usepackage{fancyhdr}
  % This line allows me to manipulate images within latex \usepackage{graphicx}
  % This package has several uses, for this document I used it to manage hyperlinks and introduce metadata to the document \usepackage{hyperref}
  % These lines define the font that I want to use in the document \usepackage{helvet} \renewcommand{\familydefault}{\sfdefault}
  \usepackage{fontspec} \usepackage{anyfontsize} \usepackage{titlesec} \newfontfamily\headingfont{Arial} \titleformat{\section}{\headingfont\Large\bfseries}{\thesection}{1em}{} \usepackage{relsize}
---
\fontspec{Arial}
```{r setup, include=FALSE}
library(lubridate)
start_date <- ymd("2023-06-19")
end_date <- today()
time_lapsed <- interval(start_date, end_date) / months(1)
time_lapsed_str <- paste0(round(time_lapsed, 0), " months")
```
# STEVEN LEUNG, Master of Data Science, PMP
- steven.leung@alumni.ucla.edu, Mobile: 604-499-3173, [LinkedIn](https://www.linkedin.com/in/stevenleung08), [GitHub](https://stevenleung2018.github.io)

\relsize{-2}
## HIGHLIGHTS OF PROFILE
- `r time_lapsed_str` of experience as Wildlife Application Specialist at Canadian Wildlife Service (CWS), Environment and Climate Change Canada (ECCC).
- Classification:
  - Currently PC-02
  - Qualified in a partially-assessed pool for EC-03 (Data Scientist/Data Engineer/Data Analyst) with Public Health Agency of Canada (PHAC)
  - Qualified in a fully-assessed pool for IT-02 (IT Analyst) with Shared Services Canada (SSC)
- Security: Reliability
- 10 years of experience as a technical consultant/project manager (with various companies)
- 4.5+ years of data & analytics client-facing consultancy experience
- Master of Data Science, UBC
- Programming/Query Languages – Python, SQL, R
- Project Management Professional (PMP) certified since 2017

## RELEVANT PROFESSIONAL EXPERIENCE
### Wildlife Application Specialist (PC-02), CWS of ECCC, June 2023-Present
- Spearhead the development of key materials, enhancing the application modernization strategy as requested by management and mandated by the Project Management Framework.
- Streamline data migration processes by crafting robust data extraction and transformation scripts, facilitating application consolidation efforts.
- Ensure timely releases (100% success rate) for the SAR-DMTS by leading UATs, collaborating with SMEs across departments, and resolving critical issues through bug fixes or workarounds, contributing to the administration of the SARA ([Species at risk public registry](https://www.canada.ca/en/environment-climate-change/services/species-risk-public-registry.html)).  
- Delivered on-time release for the NRT project in Dec 2023 by providing Python and SQL coding support, optimizing testing of PDF reports and data pipeline development.
 
### Project Consultant of A.I. / Head of Sales, ClusterTech Limited, 2016 – 2021
- Drove the full customer lifecycle consultancy for data science projects, delivering solutions from pre-sales to delivery, resulting in enhanced client satisfaction.
- Managed P&L of Sales with a focus on HPC and AI/ML/Analytics technologies, surpassing AI & Analytics targets by 209% in FY 2018-19 through strategic market segmentation and partnership development.
- Crafted complex RFP responses in collaboration with the data science team and external partners, securing lucrative contracts.

### Regional Account Manager (Asia Pacific), The Collinson Group, 2015 – 2016
- Oversaw project implementation and product/market readiness for new deals, including digital lounge programs, maintaining 100% SLA compliance since Dec 2015 through proactive account servicing.

### Business Solutions Consultant, Business Markets, SmarTone Mobile Communications Limited,	2013 – 2015
- Led productization and implementation projects for B2B products and services, transitioning from initial qualification to market launch, covering areas such as cloud solutions and mobile app development.
- Developed and implemented an ICT Training Program, boosting the department’s ICT solution selling skills.
- Conducted monthly ICT business reviews with senior management, utilizing tools like Cognos and MS Excel to inform strategic decisions.

## TECHNICAL SKILLS
- Languages: Python (PyTorch, Pandas, Numpy, Geopandas), R, SQL, MongoDB, Stan
- Microsoft 365 including MS Excel (VLOOKUP, Pivot Tables), Powerpoint, Word, Power BI and Access
- APIs: REST APIs, JSON and XML
- Project Management tools: Azure DevOps, GitHub, Trello, Microsoft Project
- Data visualization: Altair, ggplot2, Dash, Plotly, Heroku, Shiny, Kepler.gl, MS Excel, Tableau, PowerBI
- Platforms/Tools: Azure DevOps, AWS (S3, EMR, EC2), FME (Safe Software), docker, git, GitHub Actions (e.g. CI/CD), GNU make, PostgreSQL, MongoDB, Spark, Heroku, conda, VS Code, Jupyter, RStudio
- Machine learning: classification, regression, linear models, decision tree, random forest, SVM, k-NN, clustering, natural language processing, ensemble methods, deep learning with neural networks (e.g. CNNs, Autoencoders, GANs), spatial and temporal models (e.g. RNNs, LSTMs, transformers (GPT))
- Statistics & Probability: hypothesis testing, statistical inference, bootstrapping, simulations, experiment design (e.g. A/B testing)

## PUBLIC PRESENTATIONS
- [ClusterTech Demonstrates How NLP Can Facilitate in Financial Industry](https://www.youtube.com/watch?v=o7gcxLfbv0Y),	June 2020
- [Using AI to Thrive in Challenging Times - ClusterTech X Pure Storage X NVIDIA Webinar](https://www.youtube.com/watch?v=HnlXPvLIXR0),	November 2020

## RELEVANT EDUCATION
- Master of Data Science, University of British Columbia	September 2021 – June 2022
  - CGPA = 93.3% (A+ equivalent)
  - Relevant courses: Algorithms & Data Structures, Databases, Spatial & Time Series Analysis, Data Visualization, Automated Workflows, Machine Learning, NLP, Ethics (including EDI principles & bias prevention), Cloud Computing, Capstone Project
- B.Sc. in Computer Science and Engineering, University of California, Los Angeles

## [PROJECTS AT UBC](stevenleung2018.github.io)
- Capstone Project (May-Jun 2022): “Detection and Mitigation of Data Drift and Model Decay” for Goldspot Discoveries Corp.
  - Engineered an adaptable Python framework that standardizes the monitoring and detection of data drift and model decay across various datasets and models, resulting in a scalable solution for ongoing data integrity.
  - Utilized advanced tools and techniques such as PyTorch, Sci-kit Learn, Autoencoders, PCA, confidence distribution analysis, image property evaluation, and statistical tests to ensure robust performance.
- Cloud Deployment of Machine Learning Model (Mar-Apr 2022): Deploying an API on AWS to predict daily rainfall in Sydney, Australia.
  - Orchestrated the deployment of a machine learning model on AWS, leveraging EC2, S3, and EMR to process a large public dataset, enabling accurate daily rainfall predictions.
- [DoggoDash](https://doggodash.onrender.com) (Feb-Mar 2022): An interactive dashboard for recommending dogs to potential owners.
  - Created an engaging web application that recommends suitable dog breeds to prospective owners by analyzing user preferences, hosted on Heroku with dynamic visualizations powered by Plotly.
- EDAhelper (Jan-Feb 2022): Open-source software packages in Python and R for simplifying Exploratory Data Analysis.
  - Developed open-source software packages that transform complex Exploratory Data Analysis into one-line codes, streamlining the data exploration process for analysts.
- Olympic Medals (Nov-Dec 2021): A reproducible data science report on the impact of age on winning medals
  - Conducted a comprehensive study using reproducible data science techniques to test the hypothesis that age is a factor in winning Olympic medals, yielding insights into the correlation between age and athletic performance.
## VOLUNTEERING
### Mentor for MDS students, UBC, November 2023-April 2024
- Guided and supported two MDS students, providing strategic advice and fostering professional development to prepare them for successful careers post-graduation in June 2024.

## OTHER EDUCATION
- Leading for Success 10-Day Consortium Program, Executive Education, Hong Kong University of Science and Technology	2015

## SPECIALIZED TRAINING / CERTIFICATIONS
- Certified in Cybersecurity (CC) by ISC2 since December 2023
- Azure Fundamentals (AZ-900) since May 2023 
- Project Management Professional (PMP) certified (Number: 2116816)	since 2017
- Introduction to Marketing (University of Pennsylvania), 2015
- Effective Use of Microsoft Excel for Business Analysis, 2015
- Architecting on AWS, Amazon Web Services, 2015

## LANGUAGES
- Fluent in Chinese (Mandarin & Cantonese)
- Professionally Proficient in written Japanese (JLPT N1)
